In [2]:
import pandas as pd

file_path = '../cl_JUIN_2013-complet3.csv'  # Use '..' to go up one level

df = pd.read_csv(file_path, encoding='ISO-8859-1', sep=';')

df.head()

,Marque,Modèle dossier,Modèle UTAC,Désignation commerciale,CNIT,Type Variante Version (TVV),Carburant,Hybride,Puissance administrative,Puissance maximale (kW),...,HC (g/km),NOX (g/km),HC+NOX (g/km),Particules (g/km),masse vide euro min (kg),masse vide euro max (kg),Champ V9,Date de mise à jour,Carrosserie,gamme
0,ALFA-ROMEO,159,159,159 1750 Tbi (200ch),M10ALFVP000G340,939AXN1B52C,ES,non,12,147.0,...,0.052,0.032,NaN,0.002,1505,1505,715/2007*692/2008EURO5,juin-13,BREAK,MOY-SUPER
1,ALFA-ROMEO,159,159,159 2.0 JTDm (170ch) ECO,M10ALFVP000U221,939AXP1B54C,GO,non,9,125.0,...,NaN,0.169,0.190,0.003,1565,1565,715/2007*692/2008EURO5,juin-13,BERLINE,MOY-SUPER
2,ALFA-ROMEO,159,159,159 2.0 JTDm (136ch),M10ALFVP000E302,939AXR1B64,GO,non,7,100.0,...,NaN,0.149,0.175,0.001,1565,1565,715/2007*692/2008EURO5,juin-13,BERLINE,MOY-SUPER
3,ALFA-ROMEO,159,159,159 2.0 JTDm (136ch),M10ALFVP000F303,939AXR1B64B,GO,non,7,100.0,...,NaN,0.149,0.175,0.001,1565,1565,715/2007*692/2008EURO5,juin-13,BERLINE,MOY-SUPER
4,ALFA-ROMEO,159,159,159 2.0 JTDm (170ch),M10ALFVP000G304,939AXS1B66,GO,non,9,125.0,...,NaN,0.164,0.193,0.001,1565,1565,715/2007*692/2008EURO5,juin-13,BERLINE,MOY-SUPER

In [3]:
# Drop columns with high percentage of missing values
df.drop(columns=['HC (g/km)'], inplace=True)

In [4]:
from sklearn.impute import KNNImputer

# Selecting only the columns with missing values
cols_with_missing = ['HC+NOX (g/km)']

# Creating a copy of the DataFrame with only the selected columns
data_with_missing = df[cols_with_missing].copy()

# Initialize the KNN imputer
imputer = KNNImputer(n_neighbors=5)

# Fit the imputer to the data and transform it
imputed_data = imputer.fit_transform(data_with_missing)

# Convert the imputed data back to a DataFrame
imputed_df = pd.DataFrame(imputed_data, columns=cols_with_missing)

# Update the original DataFrame with the imputed values
df[cols_with_missing] = imputed_df

df[cols_with_missing].head()

   HC+NOX (g/km)
0       0.224788
1       0.190000
2       0.175000
3       0.175000
4       0.193000

In [7]:
# Impute missing values in the Particules column with moderate percentage of missing values
df['Particules (g/km)'].fillna(df['Particules (g/km)'].median(), inplace=True)

In [10]:
# Impute missing values in columns with low percentage of missing values
numeric_columns_to_impute = ['NOX (g/km)', 'CO type I (g/km)', 
                             'Consommation urbaine (l/100km)', 
                             'Consommation extra-urbaine (l/100km)',
                             'Consommation mixte (l/100km)', 
                             'CO2 (g/km)']

# Impute missing values with the mean of each numeric column
for column in numeric_columns_to_impute:
    df[column].fillna(df[column].mean(), inplace=True)

# Check if there are any missing values left
print(df.isnull().sum())

Marque                                    0
Modèle dossier                            0
Modèle UTAC                               0
Désignation commerciale                   0
CNIT                                      0
Type Variante Version (TVV)               0
Carburant                                 0
Hybride                                   0
Puissance administrative                  0
Puissance maximale (kW)                   0
Boîte de vitesse                          0
Consommation urbaine (l/100km)            0
Consommation extra-urbaine (l/100km)      0
Consommation mixte (l/100km)              0
CO2 (g/km)                                0
CO type I (g/km)                          0
NOX (g/km)                                0
HC+NOX (g/km)                             0
Particules (g/km)                         0
masse vide euro min (kg)                  0
masse vide euro max (kg)                  0
Champ V9                                235
Date de mise à jour                       0
Carrosserie                               0
gamme                                     0
dtype: int64

In [11]:
# Impute missing values in 'Champ V9' with the mode
mode_champ_v9 = df['Champ V9'].mode()[0]
df['Champ V9'].fillna(mode_champ_v9, inplace=True)

# Check if there are any missing values left
print(df.isnull().sum())

Marque                                  0
Modèle dossier                          0
Modèle UTAC                             0
Désignation commerciale                 0
CNIT                                    0
Type Variante Version (TVV)             0
Carburant                               0
Hybride                                 0
Puissance administrative                0
Puissance maximale (kW)                 0
Boîte de vitesse                        0
Consommation urbaine (l/100km)          0
Consommation extra-urbaine (l/100km)    0
Consommation mixte (l/100km)            0
CO2 (g/km)                              0
CO type I (g/km)                        0
NOX (g/km)                              0
HC+NOX (g/km)                           0
Particules (g/km)                       0
masse vide euro min (kg)                0
masse vide euro max (kg)                0
Champ V9                                0
Date de mise à jour                     0
Carrosserie                             0
gamme                                   0
dtype: int64

In [12]:
# Save the DataFrame to a new CSV file
df.to_csv('clean_data.csv', index=False)